import type { PersistedAppState } from "./storage-schema";
import { CURRENT_STORAGE_VERSION } from "./storage-schema";
import {
  DEFAULT_RECOVERY_PREFERENCES_SCHEMA,
  DEFAULT_GAMIFICATION_SETTINGS_SCHEMA,
  DEFAULT_APP_SETTINGS,
} from "./storage-schema";
import { getLocalDateKey } from "@/types/daily";

export function createDemoWorkspaceState(): PersistedAppState {
  const now = Date.now();
  const projectId = "proj-demo-webmcp";
  const quest1Id = "quest-demo-foundation";
  const mainQuestId = "quest-demo-finish-webmcp";
  const quest3Id = "quest-demo-chatgpt-flow";
  const todayKey = getLocalDateKey();

  return {
    version: CURRENT_STORAGE_VERSION,
    projects: [
      {
        id: projectId,
        name: "WEBMCP CHALLENGE",
        description: "Build an agent-native single-objective productivity workspace for distraction-prone builders.",
        status: "active",
        createdAt: new Date(now - 86400000 * 2).toISOString(),
      },
    ],
    quests: [
      {
        id: quest1Id,
        projectId,
        title: "Build product foundation",
        description: "Core UI layout, single-screen shell, and single Main Quest focus constraint.",
        status: "completed",
        priority: "high",
        progress: 100,
        estimatedMinutes: 45,
        completedAt: new Date(now - 3600000 * 18).toISOString(),
        createdAt: new Date(now - 86400000 * 2).toISOString(),
      },
      {
        id: mainQuestId,
        projectId,
        title: "Finish SIDEQUEST WebMCP Integration",
        description: "Expose document.modelContext tool handlers and ensure seamless external agent interaction.",
        status: "active",
        priority: "high",
        progress: 60,
        estimatedMinutes: 60,
        nextAction: "Test WebMCP tool actions",
        createdAt: new Date(now - 86400000).toISOString(),
      },
      {
        id: quest3Id,
        projectId,
        title: "Submit WebMCP Challenge Project",
        description: "Prepare README, verify Netlify production URL deployment and showcase Judge Demo mode.",
        status: "todo",
        priority: "medium",
        progress: 0,
        estimatedMinutes: 30,
        createdAt: new Date(now - 86400000).toISOString(),
      },
    ],
    questSteps: [
      // Quest 1 Steps (Completed)
      {
        id: "step-demo-1-1",
        questId: quest1Id,
        title: "Design minimal high-contrast dark theme tokens",
        status: "completed",
        order: 1,
        createdAt: new Date(now - 86400000 * 2).toISOString(),
        completedAt: new Date(now - 86400000 * 2 + 1800000).toISOString(),
      },
      {
        id: "step-demo-1-2",
        questId: quest1Id,
        title: "Build single active Main Quest state engine",
        status: "completed",
        order: 2,
        createdAt: new Date(now - 86400000 * 2).toISOString(),
        completedAt: new Date(now - 86400000 * 2 + 3600000).toISOString(),
      },
      // Main Quest Steps: 3 completed out of 5 = 60% progress
      {
        id: "step-demo-2-1",
        questId: mainQuestId,
        title: "Build app shell",
        status: "completed",
        order: 1,
        createdAt: new Date(now - 86400000).toISOString(),
        completedAt: new Date(now - 3600000 * 14).toISOString(),
      },
      {
        id: "step-demo-2-2",
        questId: mainQuestId,
        title: "Build Main Quest system",
        status: "completed",
        order: 2,
        createdAt: new Date(now - 86400000).toISOString(),
        completedAt: new Date(now - 3600000 * 8).toISOString(),
      },
      {
        id: "step-demo-2-3",
        questId: mainQuestId,
        title: "Add Context Keeper",
        status: "completed",
        order: 3,
        createdAt: new Date(now - 3600000 * 8).toISOString(),
        completedAt: new Date(now - 3600000 * 4).toISOString(),
      },
      {
        id: "step-demo-2-4",
        questId: mainQuestId,
        title: "Test WebMCP tool actions",
        status: "todo",
        order: 4,
        createdAt: new Date(now - 3600000 * 4).toISOString(),
      },
      {
        id: "step-demo-2-5",
        questId: mainQuestId,
        title: "Record demo",
        status: "todo",
        order: 5,
        createdAt: new Date(now - 3600000 * 2).toISOString(),
      },
      {
        id: "step-demo-2-6",
        questId: mainQuestId,
        title: "Submit project",
        status: "todo",
        order: 6,
        createdAt: new Date(now - 3600000 * 1).toISOString(),
      },
    ],
    activeMainQuestId: mainQuestId,
    focusSessions: [
      {
        id: "session-demo-1",
        questId: quest1Id,
        questTitle: "Build product foundation",
        projectName: "WEBMCP CHALLENGE",
        plannedMinutes: 25,
        elapsedSeconds: 1500,
        totalPausedSeconds: 0,
        startingProgress: 0,
        endingProgress: 100,
        startingCompletedStepIds: [],
        endingCompletedStepIds: ["step-demo-1-1", "step-demo-1-2"],
        completedStepTitles: [
          "Design minimal high-contrast dark theme tokens",
          "Build single active Main Quest state engine",
        ],
        status: "completed",
        startedAt: new Date(now - 3600000 * 18).toISOString(),
        endedAt: new Date(now - 3600000 * 17.5).toISOString(),
      },
    ],
    activeFocusSession: null,
    focusPlannedMinutes: 25,
    sideQuests: [
      {
        id: "sq-demo-1",
        title: "Redesign portfolio",
        status: "parked",
        createdAt: new Date(now - 3600000 * 6).toISOString(),
        sourceQuestId: mainQuestId,
      },
      {
        id: "sq-demo-2",
        title: "Try another animation library",
        status: "parked",
        createdAt: new Date(now - 3600000 * 4).toISOString(),
      },
      {
        id: "sq-demo-3",
        title: "Buy charger",
        status: "parked",
        createdAt: new Date(now - 3600000 * 3).toISOString(),
      },
      {
        id: "sq-demo-4",
        title: "Read new React article",
        status: "parked",
        createdAt: new Date(now - 3600000 * 2).toISOString(),
      },
    ],
    workContexts: [
      {
        id: "ctx-demo-1",
        questId: mainQuestId,
        savedAt: new Date(now - 3600000 * 2).toISOString(),
        reason: "interruption",
        note: "Where I stopped: WebMCP tools are registered. Last completed: Connected tool registry. Next: Test agent mutations against React state. Note: Need to confirm Main Quest changes persist after refresh.",
        currentStepId: "step-demo-2-4",
        nextAction: "Test agent mutations against React state",
        progress: 60,
      },
    ],
    recoveryQuests: [],
    recoveryLogs: [
      {
        id: "rec-log-demo-1",
        type: "water",
        timestamp: new Date(now - 34 * 60 * 1000).toISOString(), // 34 minutes ago
        durationSeconds: 0,
      },
      {
        id: "rec-log-demo-2",
        type: "movement",
        timestamp: new Date(now - 52 * 60 * 1000).toISOString(), // 52 minutes ago
        durationSeconds: 120,
      },
    ],
    recoveryPreferences: { ...DEFAULT_RECOVERY_PREFERENCES_SCHEMA },
    xpEvents: [
      {
        id: "xp-demo-1",
        type: "quest_completed",
        amount: 30,
        referenceId: quest1Id,
        label: "Completed: Build product foundation",
        createdAt: new Date(now - 3600000 * 18).toISOString(),
      },
      {
        id: "xp-demo-2",
        type: "step_completed",
        amount: 5,
        referenceId: "step-demo-1-1",
        label: "Step complete",
        createdAt: new Date(now - 3600000 * 18).toISOString(),
      },
      {
        id: "xp-demo-3",
        type: "step_completed",
        amount: 5,
        referenceId: "step-demo-1-2",
        label: "Step complete",
        createdAt: new Date(now - 3600000 * 18).toISOString(),
      },
      {
        id: "xp-demo-4",
        type: "focus_session_completed",
        amount: 25,
        referenceId: "session-demo-1",
        label: "Focus session (25m)",
        createdAt: new Date(now - 3600000 * 17.5).toISOString(),
      },
      {
        id: "xp-demo-5",
        type: "step_completed",
        amount: 5,
        referenceId: "step-demo-2-1",
        label: "Step complete: Build app shell",
        createdAt: new Date(now - 3600000 * 14).toISOString(),
      },
      {
        id: "xp-demo-6",
        type: "step_completed",
        amount: 5,
        referenceId: "step-demo-2-2",
        label: "Step complete: Build Main Quest system",
        createdAt: new Date(now - 3600000 * 8).toISOString(),
      },
      {
        id: "xp-demo-7",
        type: "step_completed",
        amount: 5,
        referenceId: "step-demo-2-3",
        label: "Step complete: Add Context Keeper",
        createdAt: new Date(now - 3600000 * 4).toISOString(),
      },
      {
        id: "xp-demo-8",
        type: "side_quest_parked",
        amount: 5,
        referenceId: "sq-demo-1",
        label: "Side Quest Parked: Redesign portfolio",
        createdAt: new Date(now - 3600000 * 6).toISOString(),
      },
      {
        id: "xp-demo-9",
        type: "recovery_completed",
        amount: 10,
        referenceId: "rec-log-demo-1",
        label: "Water Break",
        createdAt: new Date(now - 34 * 60 * 1000).toISOString(),
      },
      {
        id: "xp-demo-10",
        type: "recovery_completed",
        amount: 10,
        referenceId: "rec-log-demo-2",
        label: "Movement Break",
        createdAt: new Date(now - 52 * 60 * 1000).toISOString(),
      },
      {
        id: "xp-demo-11",
        type: "step_completed",
        amount: 25,
        referenceId: "first-blood",
        label: "Achievement: First Blood",
        createdAt: new Date(now - 3600000 * 18).toISOString(),
      },
      {
        id: "xp-demo-12",
        type: "focus_session_completed",
        amount: 25,
        referenceId: "locked-in",
        label: "Achievement: Locked In",
        createdAt: new Date(now - 3600000 * 17.5).toISOString(),
      },
      {
        id: "xp-demo-13",
        type: "recovery_completed",
        amount: 20,
        referenceId: "hydrated-developer",
        label: "Achievement: Hydrated Developer",
        createdAt: new Date(now - 34 * 60 * 1000).toISOString(),
      },
    ],
    dailyLoadouts: {
      [todayKey]: {
        date: todayKey,
        mainQuestId: mainQuestId,
        sideQuestIds: [quest3Id],
        recoveryGoals: [
          { type: "water", target: 3 },
          { type: "movement", target: 2 },
        ],
      },
    },
    bossConfigs: {
      [projectId]: {
        projectId,
        enabled: true,
        title: "THE WEBMCP CONQUEROR",
        phases: [
          {
            id: "phase-demo-1",
            projectId,
            title: "Phase 1: Foundation & Tokens",
            order: 1,
            questIds: [quest1Id],
          },
          {
            id: "phase-demo-2",
            projectId,
            title: "Phase 2: Live Tool Engine & Focus",
            order: 2,
            questIds: [mainQuestId],
          },
          {
            id: "phase-demo-3",
            projectId,
            title: "Phase 3: Final Deployment & Polish",
            order: 3,
            questIds: [quest3Id],
          },
        ],
      },
    },
    activeChallenge: null,
    challengeHistory: [],
    skillUnlocks: {
      "locked-in-1": new Date(now - 86400000).toISOString(),
      "closer-1": new Date(now - 3600000 * 18).toISOString(),
      "reset-1": new Date(now - 3600000 * 4).toISOString(),
    },
    unlockedAchievementIds: {
      "first-blood": new Date(now - 3600000 * 18).toISOString(),
      "locked-in": new Date(now - 3600000 * 17.5).toISOString(),
      "hydrated-developer": new Date(now - 34 * 60 * 1000).toISOString(),
    },
    playerProfile: {
      xp: 325,
      level: 4,
      lifetimeXp: 325,
      currentCombo: 3,
      bestCombo: 5,
    },
    gamificationSettings: { ...DEFAULT_GAMIFICATION_SETTINGS_SCHEMA },
    settings: {
      ...DEFAULT_APP_SETTINGS,
      onboardingCompleted: true,
      isDemoData: true,
    },
    savedAt: new Date().toISOString(),
  };
}
